[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_4mb_ota.csv
build_flags =
  -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
  -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED
  -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.1
  bblanchon/ArduinoJson @ ^7.0.4

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_8mb_ota.csv
build_flags =
  -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
  -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED
  -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.1
  bblanchon/ArduinoJson @ ^7.0.4
